### ISSUE TITLE
Compiler::setEventManager calling twice

### ISSUE THREAD

**Issue by vrkansagara** [phly/PhlyBlog#30]
Hello @weierophinney  I tried two test cases. 

(1) Without any file class or factory overriden

![image](https://user-images.githubusercontent.com/12006483/98318217-2fde7c00-2004-11eb-9eac-b94c4a298e9d.png)

(2)  Using delegators whichi is calling `setEventManager` method twice

![image](https://user-images.githubusercontent.com/12006483/98318203-2523e700-2004-11eb-8ec5-01c9dee66a55.png)

**Comment by weierophinney** [comment]
Fixed with #31
