### ISSUE TITLE
Blog compilation error [Request URI has not been set ]

### ISSUE THREAD

**Issue by vrkansagara** [phly/PhlyBlog#34]
Hello @weierophinney 

I am simply using this compile command and it give me bellow error.

~~~bash
 ./vendor/bin/laminas phly-blog:compile
~~~

![image](https://user-images.githubusercontent.com/12006483/146775913-cb6ccdc8-d278-4292-bcab-1d99d4f05878.png)

Few file I debug and found one issue relate to layout.
(1) Removal of code from master layout (layout.phtml)
~~~html
    <link rel="canonical" href="<?=$this->url('home', [], ['force_canonical' => true]); ?>" />
~~~
If I remove above line from layout.phtml ( which is master layout ) then it will work as expected. I don't know what is wrong with this.
(2) Removal of config from config.php file
~~~bash
        'base_path' => '/',
        'base_url' => '/',
~~~
If I remove above line from module config then it has no effect on error.

Would you like to help or give any hint on issue. much appreciated

**Comment by weierophinney** [comment]
The problem is the `force_canonical` option, as it requires that you have set a request URI on the router. As such, you have a couple of options.

1. Remove the `, [], ['force_canonical' => true]` syntax from the `$this->url()` call (just call it as `$this->url('home')`). This will remove the error. Your links will all be _relative_.
2. If you want fully qualified URLs, add a delegator for the `CompileCommand` class that pulls the router and injects it with a request URI:
   
   ```php
   use Laminas\Router\Http\TreeRouteStack;
   use Laminas\Uri\Http as HttpUri;
   use PhlyBlog\Console\CompileCommand;
   use Psr\Container\ContainerInterface;
   
   class BlogCompileCommandDelegator
   {
       public function __invoke(ContainerInterface $container, string $name, callable $factory): CompileCommand
       {
           $uri    = new HttpUri('https://yourdoma.in/and/path/here/');
           $router = $container->get(TreeRouteStack::class);
           $router->setRequestUri($uri;
   
           return $factory();
       }
   }
   
   // Elsewhere, in a config/autoload/*.local.php file or a ConfigProvider or a Module:
   use PhlyBlog\Console\CompileCommand;
   
   return [
       'service_manager' => [
           'delegators' => [
               CompileCommand::class => [
                   BlogCompileCommandDelegator::class,
               ],
           ],
       ],
   ];
   ```

**Comment by vrkansagara** [comment]
Awesome @weierophinney, it 's working.
