### ISSUE TITLE
Exception when running blog compile

### ISSUE THREAD

**Issue by RWOverdijk** [phly/PhlyBlog#4]
I've added this module to `composer.json` and installed. Then, I created `data/posts` and `data/blog`. Both have writing and reading access for `www`. I've copied the `sample-post.php` to `data/posts` and then ran `php ./public/index.php blog compile`. The following was my output:

rwoverdijk$ php ./public/index.php blog compile
Compiling and sorting entriesPHP Catchable fatal error:  Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/Compiler/Listener/Archives.php on line 28
PHP Stack trace:
PHP   1. {main}() /Library/WebServer/Documents/spxbeta.dev/public/index.php:0
PHP   2. Zend\Mvc\Application->run() /Library/WebServer/Documents/spxbeta.dev/public/index.php:12
PHP   3. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:297
PHP   4. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
PHP   5. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
PHP   6. Zend\Mvc\DispatchListener->onDispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
PHP   7. Zend\Mvc\Controller\AbstractController->dispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php:113
PHP   8. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php:107
PHP   9. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
PHP  10. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
PHP  11. Zend\Mvc\Controller\AbstractActionController->onDispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
PHP  12. PhlyBlog\CompileController->compileAction() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php:88
PHP  13. PhlyBlog\Compiler->compile() /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/CompileController.php:233
PHP  14. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/Compiler.php:85
PHP  15. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
PHP  16. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
PHP  17. PhlyBlog\Compiler\Listener\Archives->onCompileEnd() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464

Catchable fatal error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/Compiler/Listener/Archives.php on line 28

Call Stack:
    0.0002     226160   1. {main}() /Library/WebServer/Documents/spxbeta.dev/public/index.php:0
    0.0351    3092120   2. Zend\Mvc\Application->run() /Library/WebServer/Documents/spxbeta.dev/public/index.php:12
    0.0359    3118688   3. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:297
    0.0359    3118688   4. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
    0.0360    3120448   5. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
    0.0360    3120480   6. Zend\Mvc\DispatchListener->onDispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
    0.0445    4247760   7. Zend\Mvc\Controller\AbstractController->dispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php:113
    0.0445    4248480   8. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php:107
    0.0445    4248480   9. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
    0.0490    4637040  10. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
    0.0490    4637072  11. Zend\Mvc\Controller\AbstractActionController->onDispatch() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
    0.0490    4637296  12. PhlyBlog\CompileController->compileAction() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php:88
    0.0930    5529872  13. PhlyBlog\Compiler->compile() /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/CompileController.php:233
    0.0932    5540944  14. Zend\EventManager\EventManager->trigger() /Library/WebServer/Documents/packages/PhlyBlog/src/PhlyBlog/Compiler.php:85
    0.0932    5541160  15. Zend\EventManager\EventManager->triggerListeners() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
    0.0933    5543224  16. call_user_func() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
    0.0933    5543256  17. PhlyBlog\Compiler\Listener\Archives->onCompileEnd() /Library/WebServer/Documents/spxbeta.dev/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464

**Comment by vrkansagara** [comment]
$ php public/index.php  blog compile -a
Compiling and sorting entries............................................................................................................[ DONE ]
Compiling entries======================================================================
   The application has thrown an exception!
======================================================================
 Zend\View\Exception\RuntimeException
 Zend\View\View::render: no renderer selected!
----------------------------------------------------------------------
/home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-view/src/View.php:178
#0 /home/vallabh/git/vrkansagara.in/vendor/phly/phly-blog/src/PhlyBlog/Compiler/Listener/Entries.php(76): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#1 /home/vallabh/git/vrkansagara.in/vendor/phly/phly-blog/src/PhlyBlog/Compiler/Listener/Entries.php(50): PhlyBlog\Compiler\Listener\Entries->createEntries()
#2 /home/vallabh/git/vrkansagara.in/vendor/phly/phly-blog/src/PhlyBlog/CompileController.php(251): PhlyBlog\Compiler\Listener\Entries->compile()
#3 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): PhlyBlog\CompileController->compileAction()
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /home/vallabh/git/vrkansagara.in/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /home/vallabh/git/vrkansagara.in/public/index.php(38): Zend\Mvc\Application->run()
#14 {main}
======================================================================
   Previous Exception(s):


any one have any idea that what's wrong here.
Thanks.

**Comment by istian** [comment]
having same issue. 
used module.config.php as is, run `php public/index.php blog compile -a`.

Catchable fatal error: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in C:\Users\foobar\Development\php\myZf2Test\vendor\phly\phly-blog\src\PhlyBlog\Compiler\Listener\Archives.php on line 28

also, running `php public/index.php blog compile` with or without flags gives this:

`Compiling and sorting entries..........................................................................................................................[ DONE ]`

but then, no directory written in public folder.

**Comment by vrkansagara** [comment]
Hey @istian  can you look into the blog post file if there is any html entities have not closed properly than fix it first.

**Comment by vrkansagara** [comment]
Hi ! All commenters ,

After working so much long time on this library  , I have figured out that how it's work. Please feel free to ask me direct regarding this library. 
Thanks.
